### ISSUE TITLE
Question: not using title.crew.tsv.gz?

### ISSUE THREAD

**Issue by jimlynnjulian** [jojje/imdb-sqlite#6]
The crew file exists as far back as 2018. Why was that not downloaded? I noticed the crew are added in one of the steps on the screen:

"2024-05-11 13:46:47,432 Importing file: downloads\title.principals.tsv.gz
2024-05-11 13:46:47,435 Reading number of rows ...
2024-05-11 13:48:14,849 Inserting rows into table: crew
 91%|████████████████████████████████████████████████████████▌     | 78142310/85703817 [1:05:02<05:25, 23211.84 rows/s] "

**Comment by jojje** [comment]
Because principals `seems` a super set of `crew`. 
`crew` only contains directors and writers, while principals contain those as well, along with many other roles. So I didn't see a point in downloading the same data twice. Of the spot-checks I did of a few directors and writers from the crew file, they were all 100% accounted for in principals for their respective titles.

**Comment by jimlynnjulian** [comment]
Thanks. That has been my issue with most software from github/pypi. No photography, sound people.
Thanks again.
Jim J.
